news_posts/urls.py
from django.urls import path, include
from .views import (
    NewsPostListView,
    NewsPostDetailView,
    NewsPostCreateView,
    NewsPostUpdateView,
    NewsPostDeleteView,
    # subscribe_view,
    # unsubscribe_view,
)


app_name = 'news_posts'

urlpatterns = [
    path('', NewsPostListView.as_view(), name='news_post_list'),
    path('create/', NewsPostCreateView.as_view(), name='news_post_create'),
    path('<slug:slug>/', NewsPostDetailView.as_view(), name='news_post_detail'),
    path('<slug:slug>/update/', NewsPostUpdateView.as_view(), name='news_post_update'),
    path('<slug:slug>/delete/', NewsPostDeleteView.as_view(), name='news_post_delete'),
]

news_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_posts.urls', namespace='news_posts')),
    path('accounts/', include('user_accounts.urls', namespace='user_accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news_posts/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from .validators import validate_file_extensions
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver


def upload_file_location(instance, filename):
    """
    Returns a relative location of uploaded media files
    """
    return f'{instance.slug}/{filename}'


class NewsPost(models.Model):
    """
    Model for News post
    """
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    content = models.TextField(max_length=500)
    attachment = models.FileField(
        validators=[validate_file_extensions],
        upload_to=upload_file_location,
        null=True,
        blank=True,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Returns an absolute url to a news post
        """
        return reverse('news_posts:news_post_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-created', '-updated']


@receiver(pre_save, sender=NewsPost)
def auto_slug(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title, allow_unicode=True)


@receiver(post_delete, sender=NewsPost)
def delete_files(sender, instance, *args, **kwargs):
    instance.attachment.delete(False)

news_posts/forms.py
from django import forms
from .models import NewsPost
from ckeditor.widgets import CKEditorWidget


class NewsPostForm(forms.ModelForm):
    """
    Form for News post model
    """
    content = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = NewsPost
        fields = [
            'title',
            'content',
            'attachment',
        ]

    def clean_title(self, *args, **kwargs):
        instance = self.instance
        title = self.cleaned_data.get('title')
        qs = NewsPost.objects.filter(title__iexact=title)
        if instance is not None:
            qs = qs.exclude(pk=instance.pk)
        if qs.exists():
            raise forms.ValidationError("This title has already been used. Please try again.")
        return title

news_posts/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import (CreateView, DeleteView, DetailView, ListView, UpdateView)
from django.shortcuts import get_object_or_404
from .models import NewsPost
from .forms import NewsPostForm
from django.views.generic.edit import FormMixin
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from comments.forms import CommentForm
from comments.models import Comment
from .tasks import send_mail_notification_task


class NewsPostListView(ListView):
    """
    News post list
    """
    model = NewsPost
    template_name = 'news_post_list.html'
    context_object_name = 'news_post_list'
    paginate_by = 5


class NewsPostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Create a news post
    """
    form_class = NewsPostForm
    template_name = 'news_post_create.html'
    success_message = 'News post was successfully created.'

    def get_success_url(self):
        return self.object.get_absolute_url()

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class NewsPostUpdateView(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    """
    Update a news post
    """
    form_class = NewsPostForm
    model = NewsPost
    template_name = 'news_post_update.html'
    success_message = 'News post was successfully updated.'

    def get_object(self):
        slug = self.kwargs.get("slug")
        return get_object_or_404(NewsPost, slug=slug)

    def get_success_url(self):
        return self.object.get_absolute_url()

    def test_func(self):
        news_post = self.get_object()
        if self.request.user == news_post.author:
            return True
        return False


class NewsPostDeleteView(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin, DeleteView):
    """
    Delete a news post
    """
    model = NewsPost
    template_name = 'news_post_delete.html'
    success_url = reverse_lazy('post_list')
    success_message = 'Post was successfully removed.'

    def get_object(self):
        slug = self.kwargs.get("slug")
        return get_object_or_404(NewsPost, slug=slug)

    def test_func(self):
        news_post = self.get_object()
        if self.request.user == news_post.author:
            return True
        return False

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)


class NewsPostDetailView(SuccessMessageMixin, FormMixin, DetailView):
    template_name = 'news_post_detail.html'
    form_class = CommentForm
    success_url = "."
    success_message = 'Your comment was successfully added.'

    def get_object(self):
        slug = self.kwargs.get("slug")
        return get_object_or_404(NewsPost, slug=slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = self.form_class(self.request.POST)
        context['comment_form'] = form
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(**kwargs)
        form = context['comment_form']

        if form.is_valid():
            content_data = form.cleaned_data.get('content')
            parent_obj = None
            try:
                parent_id = request.POST['parent_id']
            except:
                parent_id = None

            if parent_id:
                parent_qs = Comment.objects.filter(id=parent_id)
                if parent_qs.exists() and parent_qs.count() == 1:
                    parent_obj = parent_qs.first()

            new_comment = Comment.objects.create(
                author=self.request.user,
                content=content_data,
                parent=parent_obj,
                post=self.object
            )

            mail_subject = 'New comment'
            current_site = get_current_site(request)
            message = render_to_string('new_comment.html', {
                'post': new_comment.post,
                'domain': current_site.domain,
            })
            to_email = new_comment.post.author.email

            send_mail_notification_task.delay(mail_subject, message, to_email)
        return self.form_valid(form)

news_posts/templates/new_comment.html
  
Someone has added a new comment to the "{{ post }}" post! Check it out! http://{{ domain }}{% url 'news_posts:news_post_detail' post.slug %}

news_posts/templates/news_post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create post{% endblock title %}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
    {{ error|escape }}
</div>
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
    <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% endif %}
<br/>
<div class="row">
    <div class="col-sm-6">
        <h1>Create Post</h1>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-success">Create Post</button>
        </form>
    </div>
</div>
<br/>
{% endblock content %}

news_posts/templates/news_post_delete.html
{% extends 'base.html' %}


{% block title %}{{object.title}}{% endblock title %}


{% block post_detail_link %}
    <li class="breadcrumb-item active">
        <a href={{ post.get_absolute_url }}>{{ object.title }}</a>
    </li>
    <li class="breadcrumb-item" aria-current="page">
        <span class="text-danger">Delete</span>
    </li>
{% endblock post_detail_link %}


{% block content %}
    <form method="post">{% csrf_token %}
        <div class="card">
            <div class="card-body">
                <h1>Delete post</h1>
                <hr />
                <p>
                    Are you sure you want to delete "{{ object.title }}"?
                </p>
                <hr />
                <button class="btn btn-danger" type="submit">Confirm</button>
            </div>
        </div>
    </form>
{% endblock content %}

news_posts/templates/news_post_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}


{% block title %}{{ object.title }} | {{ block.super }}{% endblock title %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success">
    {{ message }}
</div>
{% endfor %}
{% endif %}

<div class="card">
    <div class="card-body">
        <div class="row mx-1">
            <h1>{{ object.title }} <small>{{ object.timestamp }}</small></h1>
        </div>
        <hr/>
        <p>
            Author: {{ object.author }}
        </p>

        <hr/>

        <div class="post-detail-item">{{ object.content|linebreaks }}</div>

        <hr/>

        {% if object.attachment %}
        Attachment:
        <br/>
        <p>{{ object.attachment }}
        </p>
        <hr/>
        {% endif %}

        {% if user.is_authenticated and user == object.author or user.is_superuser %}
        <div class="btn-group w-100">
            <a
                    href="{% url 'news_posts:news_post_update' object.slug %}"
                    class="btn btn-outline-warning">
                Edit
            </a>
            <a
                    href="{% url 'news_posts:news_post_delete' object.slug %}"
                    class="btn btn-outline-danger">
                Delete
            </a>
        </div>
        <br/>
        {% endif %}
        <br/>
        <div>
            <p class="lead">
                Comment
            </p>

            {% if user.is_authenticated %}
            <form method="POST">{% csrf_token %}
                {{ comment_form|crispy }}
                <input class="btn btn-primary" type="submit" value="Post comment"/>
            </form>
            {% else %}
            <hr/>
            <p>
                You must login to comment
            </p>
            {% endif %}

            {% if object.comments.first != None %}
            <hr/>
            <br/>

            <p class="lead">
                Comments:
            </p>
            {% endif %}

            {% for comment in object.comments.all %}
            <blockquote>
                <p>
                    {{ comment.content }}
                </p>
                <cite>via {{ comment.author }}
                    | {{ comment.created|timesince }} ago
                    {% if comment.children.count > 0 %} |
                    {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %}
                    {% endif %}
                </cite>

                <div class="comment-reply">
                    <hr/>
                    {% for child_comment in comment.children %}
                    <blockquote class="blockquote ml-5">
                        <p class="mb-0">
                            {{ child_comment.content }}
                        </p>
                        <cite>
                            via {{ child_comment.author }} | {{ child_comment.created|timesince }} ago
                        </cite>
                    </blockquote>
                    {% endfor %}

                    {% if user.is_authenticated %}
                    <form method="POST" action=".">{% csrf_token %}
                        {{ comment_form|crispy }}
                        <input name="parent_id" type="hidden" value="{{ comment.id }}"/>
                        <input class="btn btn-primary" type="submit" value="Post comment"/>
                    </form>
                    {% else %}
                    <hr/>
                    <p>
                        You must login to comment
                    </p>
                    {% endif %}
                </div>
            </blockquote>

            {% if not forloop.last %}
            <hr/>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

news_posts/templates/news_post_list.html
{% extends 'base.html' %}

{% block title %}Your Posts{% endblock %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% if news_post_list %}
<br />
<div class="row">
            {% for post in news_post_list %}
                <div class="col-sm-6">
                    <div class="post-detail-item card">
                        <div class="card-body">
                            <div class="img-caption">
                                {% if post.image %}
                                    <img src="{{ post.image.url }}" class="img-fluid" />
                                    <hr />
                                {% endif %}
                                <h3>
                                    <a
                                        class="text-decoration-none"
                                        href="{{ post.get_absolute_url }}">
                                        {{ post.title }}
                                    </a>
                                    <small>{{ post.created|timesince }} ago</small>
                                </h3>
                                <hr />
                                <p>
                                    Author: {{ post.author }}
                                </p>
                                <hr />
                                {% autoescape off %}
                                {{ post.content | truncatewords_html:25 }}
                                {% endautoescape %}
                                <hr />
                                <a
                                    href="{{ post.get_absolute_url }}"
                                    class="btn btn-outline-primary"
                                    role="button">
                                    View
                                </a>

                                {% if user.is_authenticated and user == post.author or user.is_superuser %}
                                    <div class="btn-group">
                                        <a
                                            href="{% url 'news_posts:news_post_update' post.slug %}"
                                            class="btn btn-outline-warning">
                                            Edit
                                        </a>
                                        <a
                                            href="{% url 'news_posts:news_post_delete' post.slug %}"
                                            class="btn btn-outline-danger">
                                            Delete
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
{% else %}
<p>
    There are no news posts in the library.
</p>
{% endif %}
<br />
{% if is_paginated %}
<ul class="pagination justify-content-center mb-4">
    {% if page_obj.has_previous %}
    <li><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; Newer</a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">Older &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}

news_posts/templates/news_post_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}{{object.title}}{% endblock title %}

{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h1>Update Post</h1>
            <hr/>
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form|crispy }}
                <hr />
                <button type="submit" class="btn btn-outline-primary">Update Post</button>
            </form>
        </div>
    </div>
<br />
{% endblock content %}