news_posts/urls.py
from django.urls import path, include
from .views import (
    NewsPostListView,
    NewsPostDetailView,
    NewsPostCreateView,
    NewsPostUpdateView,
    NewsPostDeleteView,
    # subscribe_view,
    # unsubscribe_view,
)


app_name = 'news_posts'

urlpatterns = [
    path('', NewsPostListView.as_view(), name='news_post_list'),
    path('create/', NewsPostCreateView.as_view(), name='news_post_create'),
    path('<slug:slug>/', NewsPostDetailView.as_view(), name='news_post_detail'),
    path('<slug:slug>/update/', NewsPostUpdateView.as_view(), name='news_post_update'),
    path('<slug:slug>/delete/', NewsPostDeleteView.as_view(), name='news_post_delete'),
]

news_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_posts.urls', namespace='news_posts')),
    path('accounts/', include('user_accounts.urls', namespace='user_accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_accounts/urls.py
from django.urls import path
from .views import SignUpView, activate_account

app_name = 'user_accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate/<slug:uidb64>/<slug:token>/', activate_account, name='activate'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}News Service{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/blog-home.css' %}">
    {% block head_extra %}{% endblock head_extra %}
</head>
<body class="d-flex flex-column">
{% block body %}
  <!-- Navigation -->
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'news_posts:news_post_list' %}">News service</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                    aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainMenu">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'news_posts:news_post_create' %}">New post</a>
                                <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <form class="form-inline ml-auto">
                        <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                        <a href="{% url 'user_accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
                    </form>
                {% endif %}
            </div>
        </div>
    </nav>
<!-- Page Content -->
<div class="flex-grow-1 flex-shrink-0">
  <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    </div>
{% endblock %}
<!-- Footer -->
  <footer class="py-4 bg-dark flex-shrink-0 text-white-50">
    <div class="container text-center">
        <small>Copyright &copy; News service {% now "Y" %}</small>
    </div>
</footer>
</body>
</html>

templates/title.html
News service